version: '3.8'
services:
  ml-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-platform
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
      - "8265:8265"  # Ray dashboard
    environment:
      - RAY_DISABLE_IMPORT_WARNING=1
      - STREAMLIT_SERVER_PORT=8501
    command: >
      sh -c "
        ray start --head --port=6379 --disable-usage-stats --dashboard-host=0.0.0.0 &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
        streamlit run interface.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true
      "
    networks:
      - ml-net

networks:
  ml-net:
    driver: bridge